#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time
import shutil
import argparse
from pathlib import Path
import subprocess
WhiteList = [
    # Графика и шрифты
    "mesa_shader_cache", "nvidia", "fontconfig", "thumbnails", "icon-cache.kcache",
    
    # Система ввода и локализация
    "ibus", "ibus-table",
    
    # Среда рабочего стола (Zorin/GNOME)
    "gjs", "gnome-shell", "app-info", "wallpaper",
    
    # Пакетные менеджеры и софт
    "flatpak", "pip", "ms-playwright", "electron",
    
    # Мультимедиа и индексация
    "gstreamer-1.0", "evolution", "tracker", "tracker3"
]

def get_size(start_path='.'):
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(start_path):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            if not os.path.islink(fp):
                total_size += os.path.getsize(fp)
    return total_size / (1024 * 1024)

def clean_cache(dry_run=False, still_del=False):
    cache_path = Path.home() / ".cache"
    total_freed = 0
    total_mfreed = 0
    
    print("Cache cleaner - Версия 1")
    time.sleep(1) 
    os.system("clear")
    print(f"--== Анализ папки {cache_path} ==--")
    time.sleep(0.5)
    os.system("clear")

    dirlist = list(cache_path.iterdir())
    items = [] #to delete
    items2 = [] #white list
    items3 = [] #dry run
    items4 = [] #access less than a week

    for item in dirlist:
        try:
            size = get_size(item)
            last_access = (time.time() - item.stat().st_atime) / 86400

            if item.name in WhiteList:
                items2.append([item, size])
                continue
            if dry_run and last_access > 7:
                items3.append([item, size])
                continue
            if last_access < 7:
                if still_del:
                    items.append([item,size])
                    continue
                else:
                    items4.append([item, size, last_access])
                    continue
            else:
                items.append([item,size])
                continue

        except Exception as e:
            print(f"Error: {item.name}, {e}")


    if items != []:
        print("\n== Удаление ==")
        for item in items:
            print(f"Удаляется {item[0].name} ({item[1]:.2f} МБ) . . .", end=' ')
            try:
                if item[0].is_file():
                    item[0].unlink()
                else:
                    shutil.rmtree(item[0])
                print("готово!")
                total_freed += item[1]
            except Exception as e:
                print(f"ошибка: {e}")


    if items3 != []:
        print("\n== Можно удалить ==")
        for item in items3:
            print(f"Можно удалить {item[0].name} ({item[1]:.2f} МБ).")
            total_mfreed += item[1]
    if items4 != []:
        print("\n== Не будет удалено ==")
        for item in items4:
            print(f"Не удалено {item[0].name} ({item[1]:.2f} МБ), последний доступ: {item[2]:.1f} назад.")
    if items2 != []:
        print("\n== Белый список ==")
        for item in items2:
            print(f"{item[0].name} ({item[1]:.2f} МБ) в белом списке.")


    result = f"Можно очистить {total_mfreed:.2f} МБ кэша." if dry_run else ("Кэш не очищен, последний доступ менее 7 дней" if total_freed == 0.00 else f"Очищено {total_freed:.2f} МБ кэша.")
    subprocess.run(["notify-send", "-i", "drive-harddisk", "Чистка кэша", result])

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Программа для очистки папки ~/.cache")
    parser.add_argument("-d", "--dry-run", action="store_true",
                        help="Выполнять ли пробный запуск, с ним вывод будет содержать файлы которые можно удалить.")
    parser.add_argument("-s", "--still-del", action="store_true",
                        help="Если кэшу менее 7 дней, без этого флага он не будет удалён.")

    args = parser.parse_args()
    clean_cache(dry_run=args.dry_run, still_del=args.still_del)
    
